### ISSUE TITLE
How to ensure the async tasks run in FIFO basis?

### ISSUE THREAD

**Issue by aurrak** [robertmryan/SerialTaskDemo#1]
Greetings. A stack overflow [thread](https://stackoverflow.com/a/70586879) leads me here looking for clarifications and answers (as I do not yet have enough reputation there to post a follow up comment there).

As the demo currently stands, the `SerialTasks` ensure the async tasks running serially with one completing before starting another. However, how would one able to truly enqueue the async Tasks in a FIFO basis (similar to `addOperarion` in `OperationQueue` with maxConcurrentOperationCount == 1)? 

Consider there's a Button in a SwiftUI view (in a synchronous context) that spawns a certain number of `Tasks` (in a loop) to call into an actor for serial execution, the order of the task execution is not guaranteed (as you have very well demonstrated [here](https://stackoverflow.com/a/75967204/330686) with the `Counter` example) even though they will correctly run one after another.

So how would one solve that problem? You mentioned one may use `AsyncSequence` (e.g., an `AsyncStream` or `AsyncChannel`). I looked over your other [answer](https://stackoverflow.com/a/75730483/330686) with an `AsyncChannel` example, but it seems to me that even in that example, if you hit the buttons fast enough, the order of execution of those tasks still won't be guaranteed. Am I wrong?

How would one solve this problem if the order is important?

I have tweaked the `makeRequest` slightly to use that Counter example to demonstrate what I wanted to achieve.

```swift
import SwiftUI

struct ContentView: View {
    @StateObject var viewModel = ViewModel()

    var body: some View {
        VStack {
            Button("FIFO Test") {
                for i in 1 ... 10_000 {
                    Task { [i] in
                        let result = try await viewModel.makeRequest()
                        if i != result {
                            print(i, "does not match", result)
                        }
                    }
                }
            }
        }
        .padding()
    }
}
```

```swift
import Foundation
import os.log

// The `pointsOfInterest` log can be observed with “Points of Interest” tool in “Instruments”

private let poi = OSLog(subsystem: Bundle.main.bundleIdentifier!, category: .pointsOfInterest)

@MainActor
class ViewModel: ObservableObject {
    private let serialTasks = SerialTasks<Int>()
    private let s = Counter()

    actor Counter {
        var count: Int = 0

        func increment() -> Int {
            count += 1
            return count
        }
    }

    func makeRequest() async throws -> Int {
        // “Points of Interest” Ⓢ signpost when user initiates a request

        os_signpost(.event, log: poi, name: #function)

        return try await serialTasks.add {
            // “Points of Interest” interval for duration of the request

            let id = OSSignpostID(log: poi)
            os_signpost(.begin, log: poi, name: #function, signpostID: id)
            defer { os_signpost(.end, log: poi, name: #function, signpostID: id) }

            // some asynchronous task (in this case, making network request, parsing
            // response, and updating view model property
            return await self.s.increment()
        }
    }
}
```

**Comment by robertmryan** [comment]
A couple of observations:

 1. One should be cautious about assuming FIFO with `OperationQueue`. It considers readiness, dependencies, priorities, etc., to determine execution order. If you want strict FIFO behavior with an operation queue, you may want to make each operation dependent upon the prior one. As the [documentation](https://developer.apple.com/documentation/foundation/operationqueue#2936058) says

    > **Determine the Execution Order**
    >
    > An operation queue organizes and invokes its operations according to their readiness, priority level, and interoperation dependencies. If all of the queued operations have the same [`queuePriority`](https://developer.apple.com/documentation/foundation/operation/1411204-queuepriority) and the [`isReady`](https://developer.apple.com/documentation/foundation/operation/1412992-isready) property returns `true`, the queue invokes them in the order you added them. Otherwise, the operation queue always invokes the operation with the highest priority relative to the other ready operations.
    >
    > However, don’t rely on queue semantics to ensure a specific execution order of operations because changes in the readiness of an operation can change the resulting execution order. Interoperation dependencies provide an absolute execution order for operations, even if those operations are located in different operation queues. An operation object isn’t ready to run until all of its dependent operations have finished running.

    In short, while an operation queue *generally* “invokes them in the order you added them”, keep the above caveats in mind. In general, with `Operation`, if strict FIFO behavior is desired, it is safest to use dependencies to ensure this.

 2. This `SerialTasks` approach, itself, is definitely FIFO, because each task is strictly dependent upon the `previousTask` (and the actor eliminates races). It is logically equivalent to the `Operation` pattern of making each task dependent upon the prior task.

 3. But let us step back: With respect to launching thousands top level `Task {…}`, Swift concurrency does *not* guarantee that those launch in order that those `Task` instances were created. They run broadly in order, but not strictly so.

    As an aside, `Counter` is a poor way to confirm order of execution, because regardless of the order that the tasks run, a thread-safe rendition of `Counter` will increment the counter one-by-one, regardless of the order that the tasks actually run.

 4. To add to the confusion, if a task has an `await` suspension point, you are now subject to [actor-reentrancy](https://github.com/apple/swift-evolution/blob/main/proposals/0306-actors.md#actor-reentrancy). Swift concurrency is now free to interleave tasks and continuations.

 5. IMHO, the achilles heel of this proposed `SerialTasks` approach is the fragile handling of cancelation. You can add cancelation handling, but additional work is necessary to accomplish this. I personally now use `AsyncSequence`/`AsyncChannel` rather than this “have each task await the prior one” approach.

 6. Regarding whether `AsyncChannel` strictly honors FIFO behaviors, while I assume it does (and appears to do so), I must acknowledge that I have neither have tested this nor see any formal assurances to this end. Glancing at the [source code](https://github.com/apple/swift-async-algorithms/blob/main/Sources/AsyncAlgorithms/Channels/ChannelStateMachine.swift), the reference to `OrderedSet` of producers and consumers makes me suspect it will be FIFO, but I have not confirmed this.

 7.  You said, “the order of the task execution is not guaranteed (as you have very well demonstrated [here](https://stackoverflow.com/a/75967204/330686) with the `Counter` example) even though they will correctly run one after another”. It’s not terribly important, but the main thrust of that `Counter` example was not about order of execution, but a general observation on thread-safety. Yes, anecdotally, I noted what I mentioned in point 3, above, but I really was focusing on the thread-safety question, not FIFO. We should not conflate the thread-safety question with strict FIFO behavior (or lack thereof).

I don’t know if this answers your question, but that’s my two cents…

**Comment by aurrak** [comment]
Thanks for the very thoughtful answer. I do agree that thread-safety and FIFO are indeed two different issues.

I found some relevant discussions on the Swift forum where the community tries to come up with some queue-like mechanism to address the ordering issue. I hope one day there's a proper solution built into the language itself.

[How do you use AsyncStream to make Task execution deterministic?](https://forums.swift.org/t/how-do-you-use-asyncstream-to-make-task-execution-deterministic/57968)
[Task: Is order of task execution deterministic?](https://forums.swift.org/t/task-is-order-of-task-execution-deterministic/51553)
